export {default as Home } from './Home'
export {default as GiftRegistration} from './GiftRegistration'
export {default as RankingEdit } from './RankingEdit'
export {default as SignIn } from './SignIn'
export {default as SignUp } from './SignUp'