export {default as Home } from './Home'
export {default as PresentRegistration} from './PresentRegistration'
export {default as RankingEdit } from './RankingEdit'
export {default as Login } from './Login'
export {default as Logout } from './Logout'